// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC83Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC83() {
    driver.get("http://localhost:8081/Piattaforma_Birrifici/Home.jsp");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.linkText("Login Acquirente")).click();
    driver.findElement(By.id("in")).click();
    driver.findElement(By.name("password")).sendKeys("12345678");
    driver.findElement(By.id("in")).sendKeys("atlandi@gmail.com");
    driver.findElement(By.cssSelector(".but")).click();
    driver.findElement(By.cssSelector("b > #cerca")).click();
    driver.findElement(By.cssSelector("b > #cerca")).sendKeys("birra");
    driver.findElement(By.cssSelector(".butCerca")).click();
    driver.findElement(By.cssSelector("td .but")).click();
    driver.findElement(By.id("in")).click();
    driver.findElement(By.id("in")).sendKeys("1");
    driver.findElement(By.cssSelector("li .but")).click();
  }
}
